services:
  # ------------------------------------
  # 1. SQL SERVER (Para Booking Context)
  # ------------------------------------
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ticketmaster_sql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=TuPassword_Fuerte123! # ¡Ojo con la complejidad o falla!
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - ticketmaster-network

  # ------------------------------------
  # 2. MONGODB (Para Catalog Context)
  # ------------------------------------
  mongo:
    image: mongo:latest
    container_name: ticketmaster_mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopassword
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - ticketmaster-network

  # ------------------------------------
  # 3. RABBITMQ (Mensajería)
  # ------------------------------------
  rabbitmq:
    image: rabbitmq:3-management
    container_name: ticketmaster_rabbit
    ports:
      - "5672:5672"   # Puerto para comunicación entre apps
      - "15672:15672" # Puerto para la Interfaz Web de administración
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - ticketmaster-network

# Definición de volúmenes para persistencia
volumes:
  sqlserver_data:
  mongo_data:
  rabbitmq_data:

# Red privada para que los contenedores se vean entre sí por nombre
networks:
  ticketmaster-network:
    driver: bridge